name: goldzakatcalculator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  share_plus: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1   # <-- MESTI LETAK VERSION DI SINI

flutter_icons:                    # <-- INI MESTI BERADA DI ROOT (LEVEL SAMA DG FLUTTER)
  android: true
  ios: true
  image_path: "zakat.png"         # <-- Fail icon kau

flutter:
  uses-material-design: true
  assets:
    - zakat.png
